language: node_js
node_js:
- '5'
sudo: false
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
after_success:
- npm run report-coverage
deploy:
  provider: s3
  access_key_id: AKIAJQMBRHJAPLRIBUPA
  secret_access_key:
    secure: y+1Rs7b8p7eJIVqClzRQodusfy2qKi+Dsu2B1O7ShiaCqwHO/vbQocqDkvjkyDkBuR6vIy6gU3XZ3xoKJgx+KkNI/RrplaS0k0tk/F22Qo4ACNMQrHhiqPr3PrbtJHSwpYkjXM4lVrKPdT8Fy+97XeHQOO8iPzjvfK8FPDLgKx7AGIfRk++mbIMaUSR348zLtM8gbAc45QW5Ygo+hMSf5IrvMDBzUVG0I1vIqEPzam+hNnVbnj6g7/Nvd8cZU3o7MvkJ1qwe9Nn5k/NT6IRZSwVYxxRDXnXlh9qTIjpLHbMCBnBi362O2yN0f0uRrirWVKl6p+2+exdjMmOU3VIBtl/aTcDgHTet7cZ0ZmviZ1mLUerBK4Tg/4vEcBzzOWwYlagfJDlATjGOnLgTC+EEBOpcOTkdD5yTSh6lqFzFHChJCU1CdcgG9E5l+jh+mD9NMUUJmkl4b48sVH/sQIvvMx4mP7w5k71rh4MV/sUQX1c/2DDwi+viljWnNv+UwHVK0Ev0UezXnGmQFAdXLPA7qU3Y+WxLZYXZyFoQhbkNRgcfQ7cm1YQbAQ16bpd/qcaih25XH9BXHdm2z12JCaovjvVgdyKZi38N9hV1bit4ItNP/V4hijdQE+B+zv3YlhM8GjGsbcTZEqKy9lC3bbw7I+0AOjMCRioqMoD+FjSpE88=
  bucket: americorps
  acl: public_read
