language: node_js
node_js:
  - "5"

sudo: false

# Add cache settings
# cache:
#   directories:
#     - node_modules

install:
  - npm install

# should single run test when building production, but should
#  multi run tests when developmen, add relevant env variables
script:
  # - npm run lint
  - npm test
  # ADD DEPLOY
  # - NODE_ENV=production npm run deploy

# after_success:
#   - npm run ADD COVERAGE
