language: node_js
node_js:
  - "5"

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm test
  # ADD DEPLOY
  # - NODE_ENV=production npm run deploy

# after_success:
#   - npm run ADD COVERAGE
