language: node_js
node_js:
- '5'
sudo: false
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
- npm run build
after_success:
- npm run report-coverage
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAJHYXGOIPWOCK5R4Q
  secret_access_key: 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
  bucket: volunteer-app
  local-dir: static/dist
