language: node_js
node_js:
- '5'
sudo: false
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
after_success:
- npm run report-coverage
deploy:
  provider: s3
  access_key_id: AKIAJQMBRHJAPLRIBUPA
  secret_access_key:
    secure: l8tEql9hL+0hjR2TODzLG5b7+BKsdKF24D7xvMh2hSk9A/2Yb9ebBMqiEfC3+4Px6veVG2LKusV3MO004NcD+IGwjTDbBowUteuVriBCp1mhHVCLMH+PV32f3P8aNzVnZdBUBD8rAbfJw7TqJyhJAIxFsHssaVLKGNCFiTurGfyDbmOZ1ucbe1H7lxx4w5OxT/72qKwaQEx2+poAzVQJGw4BF1c8OqtH/fWE7m94jC3hr7SnEjKzMsyv0n+Cvw1ZAZeB1b4gtXG+8e417gHlx4GnNiYcOChDXxWpYZdlx7J2L6LtDk1aFtAjsbu2Un3wzfkscXBgh7/FDikzTDbOhJCYTyMomN1BsAO12jdXAUrjM2UIWwIDs30T9BM1VJ2cFL70+kqUGS2JJqjvK/w4ZAfANy/C+iFnXTqEqukq+jq1ADYv3o4Cryqu2ug/IikiEhpfHG+lVYp6oPPMKwAj943n8em/ggHWDSFmqt5ROIkZLilTpW+dTsbLqnKLFvwP/pcAmoniUoE3Qzldou/0ljOVc+ikipmPFrUi3GLP4/N5QCTnlqy8YCzOTh4ltwsFsN8rrW4MqEcxPCVXWD4zeYII6rZ/aNwC5qCrHaxuUly6KxEnDAHulS9/Xv2PO/Gz6/Q5gKbLghBwgOYYU5H9z0TZvey92lwqtWezeUHRpHA=
  skip_cleanup: true
