language: node_js
node_js:
- '5'
sudo: false
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
- npm run build
after_success:
- npm run report-coverage
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAJHYXGOIPWOCK5R4Q
  secret_access_key:
    secure: 0Ls/dVHAXmxJROS7er1ciHu+cS5MNPldusnQc4HkF+Fu7o4QX/Ux75/RDbBA/PMc1p1oeWYowL6C+kXYBzLPgiDnVDMlgIRlzOMflny96qf/Qjpdr2z57PaQzVs7vjqkte2qoF4wy6ELeZueVczCKBzZlFvJEWzsxwiHT3cgQHDC1VMz7sSuc7JOK7uKWBqk7goRz4QwP4WPtEzZ614IjROfgpDDRWWwRu66q8MdwXUwrMrMBAJbFSAetHF3Mjo1a9BGhn6CwyYYiVnlzlUbsqu80QnkkCtkJ5Y5n6MZ4Vfs1xKE8mmuPdsaS9GsIwqksKUkY4wGAGYAJwQDyb6sXwVwVxPukI9yQNHcgf1Nse75eJeoZ/fvHhv/wMC5V8FKfKxHE3Ur9NY7OjEl0seLMV4uqgsLGtP5vgXg4i+tKum0cOQoLH+drK+5mcV/6YuKA30pMKGInyckVHOvyeXPEP6NQtlvZ3+ziYFJBzY8jokFupeJujM9KOSGT5anEJ9xPII74OeWGRIupjT7MFTEML0iO6ENH98ZG+qUpL3gr/aNaYv6Kia/9Ud2LjpU8Bd4MgiITtLcUxT3NbuSewwbqDib5236xpv8NwdPWO042emKITFLwgFE8V+286Es0dCJRCoSqPiAdqzpd9P0fY6bijScoG3B/2zJbrPVTopVyQE=
  bucket: volunteer-app
  local-dir: static/dist
  acl: 'public_read'
